name: pressing_too
description: Application de pressing Too Pressing
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  shared_preferences: ^2.2.3

  
  printing: ^5.13.1
  pdf: ^3.11.1
  intl: ^0.19.0

  


  # FlutterFire (génération stable 2.x/4.x entre elles)
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.14.0
  

  # Google Sign-In (compatible avec la génération ci-dessus)
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo_collar.png
    - assets/icon/app_icon.png
    - assets/step_1.png
    - assets/step_2.png
    - assets/step_3.png

    - assets/hero_laundry_1.png
    - assets/hero_laundry_2.png
    - assets/hero_laundry_3.png
    - assets/hero_laundry_4.png
